tests/tests.cpp
MacOS defines another `random` function in stdlib.h
https://opensource.apple.com/source/Libc/Libc-1272.200.26/stdlib/FreeBSD/random.3.auto.html
which conflicts with lava random.
=> Fixes tests compatibility with MacOS

liblava/app/app.cpp, liblava/app/gui.cpp, liblava/app/gui.hpp
All the `app` callbacks were using `WantCaptureMouse`, so I added `gui::capture_keyboard` to check for the correct ImGui flag for handling key events.
=> Use ImGui::WantCaptureKeyboard for key callbacks

liblava/block/pipeline.cpp, liblava/block/pipeline.hpp
When creating a graphics pipeline, you need to specify the subpass it will be used in.
=> allow setting graphics pipeline subpass

liblava/resource/buffer.cpp
Buffers are not necessarily host-visible (when used e.g. for [NV_raytracing scratch buffers](https://github.com/SaschaWillems/Vulkan/blob/fcb0a2a46a7b5e84c29581756f97e258f904bc4f/examples/nv_ray_tracing_basic/nv_ray_tracing_basic.cpp#L354)) so in that case trying to map the memory results in a validation error.
Another issue is that requesting `VMA_ALLOCATION_CREATE_MAPPED_BIT` with `VMA_MEMORY_USAGE_GPU_ONLY` may or may not return mapped memory (works on most integrated GPUs). The code now checks if the memory actually got mapped before trying to copy data.
=> Check before mapping and copying buffer data

liblava/util/log.hpp
Very simple fix that prevents `setup_log` from overriding the global log level. Instead it sets the level of the newly created log directly.
=> Set created logger level instead of global log level

liblava/resource/texture.cpp
Found a small bug that happens when loading textures with stb_image that have less than 4 color channels. Using `STBI_rgb_alpha` correctly forces stb_image to convert the image to RGBA regardless of input channel count, but the returned value for `int* comp` (number of channels) always outputs the input channel count, not the final data channel count (which is always 4).
=> upload texture with correct channel count

liblava/base/base.hpp, liblava/block/pipeline.cpp, liblava/block/pipeline.hpp
I don't know how many people use this but I found it pretty useful if you want to work with a 'bindless' approach where you just stuff all your textures into one big sampler array:
```glsl
layout (constant_id = 12) const uint NUM_TEXTURES = 1;
layout (binding = 0) uniform sampler2D textures[NUM_TEXTURES];
```
Without specialization constants (or VK_EXT_descriptor_indexing) you'd have to pick a large number up front, deal with glslang limits and fill the rest of the array with fake descriptors.
At pipeline creation you can now do this:
```c++
uint32_t texture_sampler_count = scene.material_textures.size();
pipeline::shader_stage::ptr stage = make_pipeline_shader_stage(VK_SHADER_STAGE_FRAGMENT_BIT);
stage->add_specialization_entry({
.constantID = 12,
.offset = 0,
.size = …
```
=> support for specialization constants

.travis.yml, CMakeLists.txt, cmake/LavaConfig.cmake.in
This PR lets you install liblava as well as find and link it from CMake. It's an alternative to adding it as a project subdirectory and allows you to compile and use specific versions of lava. Inspired by https://github.com/liblava/liblava/issues/3.
Tested on Win 10 (MSVC) + WSL (G++ 8)
**Command line:**
```bash
mkdir build & cd build
cmake -D CMAKE_BUILD_TYPE=Release -D CMAKE_INSTALL_PREFIX=../lava-install ..
cmake --build . --target install
```
**CMakeLists.txt:**
```cmake
find_package(lava 0.5.1 REQUIRED)
add_executable(test main.cpp)
target_link_libraries(test lava::app)
```
**Command line:**
```bash
mkdir build & cd build
cmake -D CMAKE_BUILD_TYPE=Release -D lava_DIR=path/to/lava-install/lib/cmake/lava ..
cmake --build .
```
- Since all of the libraries are bundled, external headers …
=> CMake install + find_package support

CMakeLists.txt
A few small changes to allow compiling with Clang. Tested on Linux (WSL) with Clang 9 and Win 10 with clang-cl (integrated Clang coming with VS 2019).
I removed the `ALLOW_DUPLICATE_CUSTOM_TARGETS` because it doesn't seem to be doing anything. Let me know if it breaks anything on your setup.
This still doesn't allow using Clang with libc++ instead of libstc++, which is only really a concern for automated build systems. This PR was in preparation for the conan package recipe which would theoretically allow you to change the C++ lib. But libstc++ is still the standard on Linux from what I've read, and (correct me if I'm wrong) lava doesn't compile on Mac or Android where libc++ is standard.
=> Clang support

liblava/block/block.cpp
Minor change to make the [best practices validation layer](https://vulkan.lunarg.com/doc/view/1.1.126.0/windows/best_practices.html) happy.
> [warning] Validation Performance Warning: [ UNASSIGNED-BestPractices-vkCreateCommandPool-command-buffer-reset ] Object 0: handle = 0x181084581d0, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x8728e724 | vkCreateCommandPool(): VK_COMMAND_POOL_CREATE_RESET_COMMAND_BUFFER_BIT is set. Consider resetting entire pool instead.
> VK_COMMAND_POOL_CREATE_RESET_COMMAND_BUFFER_BIT allows any command buffer allocated from a pool to be individually reset to the initial state; either by calling vkResetCommandBuffer, or via the implicit reset when calling vkBeginCommandBuffer. If this flag is not set on a pool, then vkResetCommandBuffer must not be called for any …
=> Create command pools without reset flag

liblava/core/data.hpp
Tiny fix that allows using `align_up` with things like `glm::uvec3`:
```c++
glm::uvec3 groups = lava::align_up(glm::uvec3(scene.main_camera.viewport.zw, 1u), THREADS) / THREADS;
app.device->call().vkCmdDispatch(cmd_buf, groups.x, groups.y, groups.z);
```
Without this change, I'm getting:
> Error C2676 binary '-': 'glm::vec<3,glm::uint,glm::packed_highp>' does not define this operator or a conversion to a type acceptable to the predefined operator
=> allow using align_up with types that don't have operator-(int)

liblava/app/gui.cpp
This change aligns font icons horizontally by making imgui create a font atlas with fixed icon glyph size.
before:
after:
If you think this might be unwanted in some scenarios (although I can't personally think of any), I could also put this behind a setting.
=> Align font icons

liblava/app/forward_shading.cpp
I found a few issues with the [synchronization validation](https://vulkan.lunarg.com/doc/sdk/1.2.148.0/windows/synchronization_usage.html) from the latest SDK.
- src stage doesn't need bottom of pipe, `COLOR_ATTACHMENT_OUTPUT` and `LATE_FRAGMENT_TESTS` is all we need to wait for attachment writes
- dst stage needs to include `EARLY_FRAGMENT_TESTS` since that's where depth/stencil load ops happen (in this case: clear)
- dst access mask also needs to consider depth/stencil writes
- src stage needs `LATE_FRAGMENT_TESTS` to wait for depth attachment writes
- src access mask also needs to consider depth/stencil writes
- dst access mask includes memory writes to prevent write-after-write (although you could possibly argue that writing to an attachment would require a layout transition, at which …
=> Fix external subpass dependencies

liblava/base/memory.cpp, liblava/base/memory.hpp
Tiny change that allows you to set a custom `VmaAllocator` handle in `allocator` if you need different function pointers, creation flags, etc.
=> custom allocator support

liblava/resource/buffer.cpp, liblava/resource/buffer.hpp
Fairly useful to have for the raytracing extensions, but also for neat stuff like [buffer references](https://developer.nvidia.com/blog/improved-glsl-syntax-vulkans-descriptorset-indexing/). But if you think it's too specific to add to lava, that's fine.
re: the function pointer check: the spec [says](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/vkGetDeviceProcAddr.html) `vkGetDeviceProcAddr` returns `nullptr` for functions of extensions that are not enabled.
=> Add support for getting buffer address (VK_KHR_buffer_device_address)

liblava/file/file.cpp
This fixes a bug that got introduced in https://github.com/liblava/liblava/commit/36390da6a60b093fba25b6a2ddc9541fa6813992. `seek` with one argument only takes an offset, and `ios_base::seekdir::end` is implicitly converted to 2, so `get_size` always returned a size of 2.
=> Fix for file::get_size

liblava/app/app.cpp, liblava/app/imgui.cpp, liblava/app/imgui.hpp, liblava/resource/format.cpp, liblava/resource/format.hpp
Just tried out your changes for sRGB backbuffer support and it works great, thanks 👍 
This PR is an attempt at fixing the remaining issue with imgui colors assuming a non-sRGB backbuffer. `app` now converts the colors from sRGB to linear if it detects `target` using an sRGB format.
There are two more changes:
- users can override the imgui style in the config before `app.setup` to make sure their style gets the same color conversion treatment. if that's unwanted, they can change the style after `app.setup`
- if the swapchain supports all formats, it picks the first from the list of requested formats, not hardcoded `BGRA8_UNORM`
Old (and new) behavior with non-sRGB backbuffer:
Old behavior with sRGB backbuffer:
New behavior with sRGB backbuffer:
The result isn't exactly equal, but I'd say …
=> Fix for incorrect imgui theme colors with sRGB backbuffer

CMakeLists.txt
@TheLavaBlock after merging, can you add a tag for 0.6.2, please? Then I can update the conan recipe and work on the vcpkg port.
=> Fix VMA include installation

CMakeLists.txt
Sorry for all the build system PR spam... This should hopefully be the last one to make vcpkg work 🙏 
`install(DIRECTORY ...)` with a file pattern still copies empty folders even if there are no matching files in them. vcpkg doesn't like that and aborts installation. Workaround is to manually get a list of all files and install them directly.
I've verified that this works with standard install targets using a simple imgui demo window.
=> Skip empty include dirs during install

liblava/block/graphics_pipeline.cpp, liblava/block/graphics_pipeline.hpp
I've been using Liblava for a variety of things recently, and I felt like it could've used an easy way to set primitive topology on a pipeline. I read #26, but in my opinion that is not a very obvious solution from the perspective of somebody without deep knowledge of this library, and I think that setting primitive topology is a very basic use-case. Using a function like this was the way I assumed I would be able to do it, and the current way doesn't seem to be documented yet in the guide / tutorial.
=> Added a setter for input assembler topology

liblava/app/camera.cpp, liblava/app/camera.hpp
I wanted to make an MVP matrix on CPU, and saw that the camera's view and projection matrices are private, so I added getter methods for them, as well as a combined view/projection matrix for convenience.
=> Added camera matrix getters

liblava-demo/triangle.cpp, liblava/resource/mesh.hpp
I've gotten pretty confused working with all these different branches of Liblava! After updating my FBX project to latest Liblava, I realized that ``mesh_data`` had broken (it currently isn't tested by any samples here). Then I somehow changed branches by accident and thought it was working. Then I realized it definitely _wasn't_ working.
Anyways, this PR fixes the ``mesh_data`` compilation errors on my project that implemented it before I refactored generic meshes.
=> Fixed mesh data regression

liblava/resource/mesh.hpp
I needed to flip a mesh by {1, -1, 1}, so I wrote this. By taking in a 3 element vector this way, it could also be used to make meshes fatter or taller.
=> Added a scale by vector method to mesh data

liblava/resource/mesh.hpp
I wrote a bug in my previous pull request that was not caught by the current samples. This fixes it.
=> Fixed vertex buffer stride

liblava/app/camera.cpp, liblava/app/camera.hpp
I use the [Hands Down](https://sites.google.com/alanreiser.com/handsdown) family instead of the QWERTY keyboard layout, and I use [home-row mod keys](https://precondition.github.io/home-row-mods). For these reasons, I (and anybody else with this fairly popular kind of setup, at least among keyboard nerds) need the inputs to be rebindable to one or multiple keys. In my current project, I now have this line:
```c++
app.camera.set_movement_keys({lava::key::m},
{lava::key::n, lava::key::left_control},
{lava::key::s, lava::key::left_super},
{lava::key::t, lava::key::left_alt});
```
This PR keeps WASD as the default control scheme.
=> Made camera controls customizable

liblava/resource/mesh.hpp
It is difficult to use generation of planes for anything useful, because I can't get a ``lava::mesh_data_template<T>`` object that can then by translated, scaled, and rotated. This pr separates creation of primitive meshes from mesh_data objects. It is backwards compatible, so no changes have been made to the sample projects.
=> Separate primitive mesh data creation

liblava/base/device.cpp, liblava/base/device.hpp
This is a pretty low-tech way to make VkPhysicalDevice2 work in my project. As discussed in the Discord server, there's currently no very clear way to do this. I thought about ways to automate this, because I feel like C++ should provide some metaprogramming tools to figure out if we have a VkPhysicalDevice or VkPhysicalDevice2, but nothing that I tried work.
=> Added support for VkPhysicalDevice2

liblava/core/hex.hpp, liblava/frame/input.hpp
To be able to compile in macos I had to do two changes:
1. std::unordered_map is used in livlava/core/hex.hpp in line 56 and there is no #inlcude<unordered_map> defined.
2. The function tooltips.emplace_back in liblava/app/app.hpp uses the tooltip struct but it requires a constructor, as the tooltip doesn't have a constructor the function fails with the error "..no matching function for call to 'construct_at'..". So a constructor was added to struct tooltip.
=> Macos build

liblava/base/base.hpp, liblava/frame/renderer.cpp, liblava/frame/renderer.hpp, liblava/resource/buffer.cpp, liblava/resource/buffer.hpp
A proposal to my Issue #95. 
This change allows to add your own wait/signal semaphores to the vkQueueSubmit call in renderer::end_frame.
Allowing to synchronize additional command buffers with the main render frame command buffers. (useful when working mit multiple command queues). 
Support for timeline semaphores could be interesting too. (set via .pNext for vkQueueSubmit)
=> Added support for user definable semaphores to renderer to synchronization with own command buffers. 

liblava/app/imgui.cpp, liblava/frame/window.cpp, liblava/frame/window.hpp
By default the mouse coordinates are in the wrong scale.
I haven't checked this on high-dpi windows or linux screens, so this patch may not be correct for them.
original behaviour:
https://user-images.githubusercontent.com/58549/218182791-0d947f25-1438-4423-a79f-51eae223deb7.mp4
fixed behaviour:
https://user-images.githubusercontent.com/58549/218182770-07891e0d-9555-486a-ad4a-a7a2e0a079e1.mp4
=> Fixes mouse coordinates for macos retina screens.

liblava/base/base.cpp, liblava/base/instance.cpp, liblava/frame/renderer.cpp
A possible fix for my Issue #99.
By recreating the Swapchain as a result of `VK_SUBOPTIMAL_KHR` in addition to `VK_ERROR_OUT_OF_DATE_KHR` the next call to
`vkAcquireNextImageKHR` doesn't fail anymore.
In addition i prevented the validation error "VUID-VkSwapchainCreateInfoKHR-imageExtent-01274" to cause an assertion error.
This is neccesary due to an "oversight" in the specification https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/1340.
If the window is resized between the call to get the new window size and the creation of the Swapchain this validation error is triggered.
This cant be caught, but the application recovers (if we don't kill it via assertion).
It may be a good idea to not log a critical message in `check`  for `VK_SUBOPTIMAL_KHR`, this I have not implemented.
=> Fix for Swapchain VK_SUBOPTIMAL_KHR crash on Linux
